# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ccReIm-SJ8y4vypZU3mskfMlufG7hnLl
"""

import streamlit as st
import tensorflow as tf
import numpy as np

# የገጹ ርዕስ እና መግለጫ
st.set_page_config(page_title="የስሜት ትንተና (Sentiment Analysis)", page_icon="🧠")
st.title("🧠 ፊልም/ምርት ግምገማ መተንተኛ")
st.write("አስተያየትዎን ከታች ያስገቡ፣ ሞዴሉ 'Positive' ወይም 'Negative' መሆኑን ይነግርዎታል።")

# 1. ሞዴሉን እና ቬክተራይዘሩን መጫን (Cache በማድረግ ፍጥነቱን ይጨምራል)
@st.cache_resource
def load_assets():
    model = tf.keras.models.load_model("sentiment_bilstm_model.keras")
    vec_model = tf.keras.models.load_model("vectorizer.keras")
    return model, vec_model.layers[0]

try:
    model, vectorizer = load_assets()
    st.success("✅ ሞዴሉ በተሳካ ሁኔታ ተጭኗል!")
except Exception as e:
    st.error(f"❌ ፋይሎቹን መጫን አልተቻለም፦ {e}")

# 2. የተጠቃሚ ግብዓት (User Input)
user_text = st.text_area("አስተያየት እዚህ ይጻፉ...", placeholder="ለምሳሌ፦ This movie was incredible!")

if st.button("ተንትን"):
    if user_text.strip() != "":
        # ጽሑፉን ወደ ቁጥር መለወጥ
        vec_text = vectorizer([user_text])

        # ግምት ማግኘት
        prediction = model.predict(vec_text, verbose=0)[0][0]

        # ውጤቱን ማሳየት
        st.divider()
        if prediction >= 0.5:
            st.balloons() # ደስታን ለመግለጽ
            st.subheader(f"ውጤት፦ 😊 Positive")
            st.progress(float(prediction))
            st.write(f"እርግጠኝነት (Score)፦ {prediction:.2f}")
        else:
            st.subheader(f"ውጤት፦ 😞 Negative")
            st.progress(float(prediction))
            st.write(f"እርግጠኝነት (Score)፦ {prediction:.2f}")
    else:
        st.warning("እባክዎ መጀመሪያ ጽሑፍ ያስገቡ።")
